title: Rakhil Pilachrey Resume
profile_img: /assets/img/profile.webp
icon_img: /assets/img/icon.webp
url: https://rakhil-pilachrey.github.io

name: "Rakhil Pilachrey"
job: "Senior Platform Engineer"

phone_number: +44 7767978835
address: London, United Kingdom
email: rakhilravindran007@gmail.com
linkedin_username: linkedin
github_username: github
instagram_username:
twitter_username:
facebook_username:
youtube_username:
blog_url: homepage-url

# If your repo name follows the format "<user-name>.github.io", then leave the below blank.
# Otherwise, set its value as "/<repo-name>". ex) baseurl: /resume
baseurl: ""

exclude:
  - _posts/
  - resources/
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag